# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Object1(object):
    def setupUi(self, Object1):
        Object1.setObjectName("Object1")
        Object1.resize(830, 513)
        self.centralwidget = QtWidgets.QWidget(Object1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 341, 71))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(370, 40, 392, 271))
        self.calendarWidget.setObjectName("calendarWidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 330, 781, 51))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 136, 321, 101))
        self.plainTextEdit.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 261, 41))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 260, 151, 51))
        self.pushButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(200, 260, 150, 51))
        self.dateEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.dateEdit.setObjectName("dateEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 390, 521, 51))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(25, 17, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        Object1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Object1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 26))
        self.menubar.setObjectName("menubar")
        Object1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Object1)
        self.statusbar.setObjectName("statusbar")
        Object1.setStatusBar(self.statusbar)

        self.retranslateUi(Object1)
        QtCore.QMetaObject.connectSlotsByName(Object1)

    def retranslateUi(self, Object1):
        _translate = QtCore.QCoreApplication.translate
        Object1.setWindowTitle(_translate("Object1", "MainWindow"))
        self.label.setText(_translate("Object1", "Трекер событий!"))
        self.label_2.setText(_translate("Object1", "Описание события"))
        self.pushButton.setText(_translate("Object1", "Установить"))
        self.label_3.setText(_translate("Object1", "До события осталось:  XX дней"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Object1 = QtWidgets.QMainWindow()
    ui = Ui_Object1()
    ui.setupUi(Object1)
    Object1.show()
    sys.exit(app.exec_())
