# Generated by Django 4.1.7 on 2023-04-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoOfWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
