# Generated by Django 4.1.7 on 2023-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0004_calculatetableex_calculatetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
