# Generated by Django 4.1.7 on 2023-04-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0011_alter_review_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
    ]
