# Generated by Django 4.1.7 on 2023-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0014_alter_review_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='reviews/default_review.jpg', upload_to='reviews/'),
        ),
    ]
