# Generated by Django 4.1.7 on 2023-04-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0015_alter_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=4000)),
                ('image_works', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_1.typeofservices')),
            ],
        ),
    ]
