# Generated by Django 4.1.7 on 2023-04-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0016_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image_works',
        ),
        migrations.AddField(
            model_name='typeofservices',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_1.company'),
        ),
    ]
