# Generated by Django 4.1.7 on 2023-05-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0017_remove_company_image_works_typeofservices_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatetableex',
            name='title',
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='dismantling',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='montage',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='plaster',
            field=models.IntegerField(default=450),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='putty',
            field=models.IntegerField(default=160),
        ),
    ]
