# Generated by Django 4.1.7 on 2023-05-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_1', '0018_remove_calculatetableex_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatetableex',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
