# Generated by Django 4.1.7 on 2023-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0021_alter_calculatetableex_dismantling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatetableex',
            name='dismantling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='montage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='plaster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='putty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
