# Generated by Django 4.1.7 on 2023-05-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0022_alter_calculatetableex_dismantling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatetableex',
            old_name='user',
            new_name='owner',
        ),
    ]
