# Generated by Django 4.1.7 on 2023-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0023_rename_user_calculatetableex_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatetableex',
            name='dismantling',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='montage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='plaster',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatetableex',
            name='putty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
