# Generated by Django 4.1.7 on 2023-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0024_alter_calculatetableex_dismantling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismantling', models.IntegerField()),
                ('montage', models.IntegerField()),
                ('plaster', models.IntegerField()),
                ('putty', models.IntegerField()),
            ],
        ),
    ]
